name: Hello world workflow

on:
   push:
     branches:
      - main
   pull request:
     branches:
      - main
   workflow_dispatch:

jobs:
    hello:
      runs-on: ubuntu-lastest
      steps:
        - uses: actions/checkout@v2
        - name: hello-world
          run: echo "Hello World"
          shell: bash

    goodbye:
      runs-on: ubuntu-lastest
      steps:
        - name: goodbye world
          run: echo"Goodbye world"
          shell: bash
